"""empty message

Revision ID: 2056eed77237
Revises: b05926ee987b
Create Date: 2025-04-02 16:03:12.456412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2056eed77237'
down_revision: Union[str, None] = 'b05926ee987b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'comment_id')
    # ### end Alembic commands ###
