"""empty message

Revision ID: 4eb67a9862d6
Revises: 8a5bcdc92694
Create Date: 2025-03-19 23:34:09.290868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb67a9862d6'
down_revision: Union[str, None] = '8a5bcdc92694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('experience', sa.Integer(), nullable=True))
    op.add_column('task_asignees', sa.Column('executor_id', sa.Integer(), nullable=True))
    op.add_column('task_asignees', sa.Column('requester_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_asignees_user_id_fkey', 'task_asignees', type_='foreignkey')
    op.create_foreign_key(None, 'task_asignees', 'users', ['requester_id'], ['id'])
    op.create_foreign_key(None, 'task_asignees', 'users', ['executor_id'], ['id'])
    op.drop_column('task_asignees', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_asignees', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_asignees', type_='foreignkey')
    op.drop_constraint(None, 'task_asignees', type_='foreignkey')
    op.create_foreign_key('task_asignees_user_id_fkey', 'task_asignees', 'users', ['user_id'], ['id'])
    op.drop_column('task_asignees', 'requester_id')
    op.drop_column('task_asignees', 'executor_id')
    op.drop_column('employees', 'experience')
    # ### end Alembic commands ###
