"""empty message

Revision ID: 542bcbabfef9
Revises: 3a7c142f478b
Create Date: 2025-03-23 19:10:25.833245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542bcbabfef9'
down_revision: Union[str, None] = '3a7c142f478b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('boss_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'employees', ['boss_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'boss_id')
    # ### end Alembic commands ###
