"""empty message

Revision ID: 779d6d08292e
Revises: c37748c6b786
Create Date: 2025-03-30 18:45:20.767450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779d6d08292e'
down_revision: Union[str, None] = 'c37748c6b786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tag', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('epic_task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['epic_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'epic_task_id')
    op.drop_column('tasks', 'tag')
    # ### end Alembic commands ###
