"""empty message

Revision ID: 7f99f625e4f4
Revises: bdef66eaf8ef
Create Date: 2025-04-06 15:09:31.582787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f99f625e4f4'
down_revision: Union[str, None] = 'bdef66eaf8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_task_history', sa.Column('user_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_task_history', 'user_name')
    # ### end Alembic commands ###
