"""empty message

Revision ID: 828f246f233d
Revises: 5736f620d26e
Create Date: 2025-05-06 16:21:25.215771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828f246f233d'
down_revision: Union[str, None] = '5736f620d26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_asignees_user_id_fkey', 'project_asignees', type_='foreignkey')
    op.drop_constraint('project_asignees_project_id_fkey', 'project_asignees', type_='foreignkey')
    op.create_foreign_key(None, 'project_asignees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_asignees', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_asignees', type_='foreignkey')
    op.drop_constraint(None, 'project_asignees', type_='foreignkey')
    op.create_foreign_key('project_asignees_project_id_fkey', 'project_asignees', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('project_asignees_user_id_fkey', 'project_asignees', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
