"""empty message

Revision ID: 89881db8272b
Revises: 542bcbabfef9
Create Date: 2025-03-24 23:06:44.345643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89881db8272b'
down_revision: Union[str, None] = '542bcbabfef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_name', sa.String(), nullable=False))
    op.alter_column('attachments', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'attachments', ['file_path'])
    op.create_unique_constraint(None, 'attachments', ['file_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='unique')
    op.drop_constraint(None, 'attachments', type_='unique')
    op.alter_column('attachments', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('attachments', 'file_name')
    # ### end Alembic commands ###
