"""empty message

Revision ID: aa08982c71e6
Revises: a1ca887f9c14
Create Date: 2025-04-05 18:48:32.808393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa08982c71e6'
down_revision: Union[str, None] = 'a1ca887f9c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'rating')
    op.add_column('tasks', sa.Column('update_wait_time', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('update_in_progress_time', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('update_done_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating')
    op.drop_column('tasks', 'update_done_time')
    op.drop_column('tasks', 'update_in_progress_time')
    op.drop_column('tasks', 'update_wait_time')
    op.add_column('employees', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
