"""empty message

Revision ID: cbf397ac4454
Revises: 89881db8272b
Create Date: 2025-03-26 00:29:26.022984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf397ac4454'
down_revision: Union[str, None] = '89881db8272b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_asignees', sa.Column('requestor_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_asignees_requester_id_fkey', 'task_asignees', type_='foreignkey')
    op.create_foreign_key(None, 'task_asignees', 'users', ['requestor_id'], ['id'])
    op.drop_column('task_asignees', 'requester_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_asignees', sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_asignees', type_='foreignkey')
    op.create_foreign_key('task_asignees_requester_id_fkey', 'task_asignees', 'users', ['requester_id'], ['id'])
    op.drop_column('task_asignees', 'requestor_id')
    # ### end Alembic commands ###
