"""empty message

Revision ID: e73fbc721be9
Revises: 72558a581fbd
Create Date: 2025-04-04 13:25:44.622703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73fbc721be9'
down_revision: Union[str, None] = '72558a581fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attachments_file_name_key', 'attachments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('attachments_file_name_key', 'attachments', ['file_name'])
    # ### end Alembic commands ###
